COST_COMPUTER:
  FALLEN_EVENTS_COST_WEIGHT: 0.0
  MAX_PAIRWISE_TRACKLET_DISTANCE: 1000
  MAX_SELF_LOCALIZATION_MATCHING_DISTANCE: 9000
  MIN_TRACKLET_LIFETIME: 50
  NUMBER_DETECTION_COST_WEIGHT: 0.0
  PAIRWISE_COSTS_OFFSET: -0.05711324200406234
  PAIRWISE_DISTANCE_COST_NORMALIZER: 500
  SELF_LOCALIZATION_COST_WEIGHT: 0.4167136220011788
  TEAM_DETECTION_COST_WEIGHT: 0.08400050033150826
  TRACKLET_LIFETIME_COST_WEIGHT: 0.2437594035456458
  TRACKLET_TO_TRACKLET_COST_WEIGHT: 0.2555264741216671
  UNARY_COSTS_OFFSET: -0.20319215205599472
GLOBAL_OPTIMIZER:
  NUM_TRACKS: 10
  TIME_LIMIT: 240
MISC:
  IGNORE_PENALIZED_PLAYERS: true
  PENALIZED_EVENT_DELAY: 0
NUMBER_DETECTOR:
  DEVICE: cuda:0
  SCORE_THRESH: 0.8
  WEIGHTS: models/number_detection/model_00004.pth
TEAM_DETECTOR:
  DEVICE: cuda:0
  SCORE_THRESH: 0.8
  WEIGHTS: models/team_detection/best_weights.pth
TRACKER:
  ACTIVE_TRACKS_NMS_THRESH: 0.8
  IGNORE_BALLS: true
  INACTIVE_PATIENCE: 1
  MAX_ACTIVE_TRACKS: 15
  NEW_TRACKS_NMS_THRESH: 0.3
  OBJECT_DETECTOR:
    CONFIG: configs/object_detection/faster_rcnn/r50/r50_high_res.yaml
    WEIGHTS: models/object_detection/faster_rcnn/r50_high_res_28-08-2022_01-09/model_0017499.pth
  SIGMA_ACTIVE: 0.5
