# UNARY_COSTS_OFFSET:
#   LOWER_BOUND: -1.5
#   UPPER_BOUND: 0.0
#   NUM_VALUES: 16
# PAIRWISE_COSTS_OFFSET:
#   LOWER_BOUND: -1.0
#   UPPER_BOUND: 0.0
#   NUM_VALUES: 16
SELF_LOCALIZATION_COST_WEIGHT:
  LOWER_BOUND: 1.0
  UPPER_BOUND: 1.0
  NUM_VALUES: 1
TEAM_DETECTION_COST_WEIGHT:
  LOWER_BOUND: 1.0
  UPPER_BOUND: 1.0
  NUM_VALUES: 1
TRACKLET_LIFETIME_COST_WEIGHT:
  LOWER_BOUND: 1.0
  UPPER_BOUND: 1.0
  NUM_VALUES: 1
TRACKLET_TO_TRACKLET_COST_WEIGHT:
  LOWER_BOUND: 1.0
  UPPER_BOUND: 1.0
  NUM_VALUES: 1